spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pix
    username: local_user
    password: local_password
    hikari:
      pool-name: pix-dev-pool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 35000
      idle-timeout: 35000
      max-lifetime: 1800000
      validation-timeout: 5000
      auto-commit: false
      leak-detection-threshold: 20000
      data-source-properties:
        ApplicationName: pix-keys-api-dev
        reWriteBatchedInserts: true
        tcpKeepAlive: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  metrics:
    tags:
      application: pix-keys-api
      env: dev
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms,100ms,250ms,500ms,1s,2s
