server:
  shutdown: graceful
  forward-headers-strategy: native

spring:
  profiles:
    active: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      pool-name: ${HIKARI_POOL_NAME:pix-prod-pool}
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:30}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      connection-timeout: ${HIKARI_CONN_TIMEOUT_MS:30000}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT_MS:600000}
      max-lifetime: ${HIKARI_MAX_LIFETIME_MS:1800000}
      validation-timeout: ${HIKARI_VALIDATION_TIMEOUT_MS:5000}
      auto-commit: false
      leak-detection-threshold: ${HIKARI_LEAK_DETECTION_MS:0}
      data-source-properties:
        ApplicationName: ${APP_NAME:pix-keys-api}
        reWriteBatchedInserts: true
        tcpKeepAlive: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE:health,info,prometheus}
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: ${APP_NAME:pix-keys-api}
      env: prod
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms,100ms,250ms,500ms,1s,2s

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
